
 make.py started: 2016-08-01 11:53:52 /Users/Frank/Desktop/gslab_python/mental_coupons 


Path: gslab_make
URL: https://econ-gentzkow-svn.stanford.edu/repos/main/trunk/lib/python/gslab_make
Repository Root: https://econ-gentzkow-svn.stanford.edu/repos/main
Repository UUID: 89b4331b-4301-411a-8e06-9c78d9cdb83d
Revision: 34785
Node Kind: directory
Last Changed Author: jwchoi2
Last Changed Rev: 33502
Last Changed Date: 2016-02-07 17:40:17 -0800 (Sun, 07 Feb 2016)


 get_externals.py started: 2016-08-01 11:53:52 /Users/Frank/Desktop/gslab_python/mental_coupons

 Input was: "33988	%svn%/lib/stata/gslab_misc	*	./lib/stata/gslab_misc	""""".
SVN command passed: https://econ-gentzkow-svn.stanford.edu/repos/main/trunk/lib/stata/gslab_misc/ @33988 exported to ./external/./lib/stata/gslab_misc/.

 Input was: "33988	%svn%/lib/third_party/stata_tools	*	./lib/third_party/stata_tools	""""".
SVN command passed: https://econ-gentzkow-svn.stanford.edu/repos/main/trunk/lib/third_party/stata_tools/ @33988 exported to ./external/./lib/third_party/stata_tools/.

 get_externals.py ended: 2016-08-01 11:53:55


Execute:  statamp -e do "setup.do"
/bin/sh: statamp: command not found
ERROR! Command statamp -e do "setup.do" executed with errors 
Command 'statamp -e do "setup.do"' returned non-zero exit status 127


Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gslab_make/py/run_program.py", line 52, in run_stata
    run.move_log(default_log)
  File "/Library/Python/2.7/site-packages/gslab_make/py/private/runprogramdirective.py", line 238, in move_log
    raise CritError(messages.crit_error_no_file % default_log)
CritError: 'ERROR! File test/setup.log not found'


Execute:  python  "run_all_tests.py" 
test_ivreg (test_ivreg.test) ... ERROR
test_qtfit (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: test_ivreg (test_ivreg.test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Frank/Desktop/gslab_python/mental_coupons/test/test_ivreg.py", line 12, in test_ivreg
    test_input = pd.read_csv('../temp/ivreg_test_input.csv')
  File "/Library/Python/2.7/site-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Library/Python/2.7/site-packages/pandas/io/parsers.py", line 315, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Library/Python/2.7/site-packages/pandas/io/parsers.py", line 645, in __init__
    self._make_engine(self.engine)
  File "/Library/Python/2.7/site-packages/pandas/io/parsers.py", line 799, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Library/Python/2.7/site-packages/pandas/io/parsers.py", line 1213, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 358, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3427)
  File "pandas/parser.pyx", line 628, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6861)
IOError: File ../temp/ivreg_test_input.csv does not exist

======================================================================
ERROR: test_qtfit (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_qtfit
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/Frank/Desktop/gslab_python/mental_coupons/test/test_qtfit.py", line 4, in <module>
    import pyqt_fit.kernels as kernels
ImportError: No module named pyqt_fit.kernels


----------------------------------------------------------------------
Ran 2 tests in 0.006s

FAILED (errors=2)

 make.py ended: 2016-08-01 11:53:56
